### ISSUE TITLE
Second Type: single page app

### ISSUE THREAD

**Issue by effordDev** [jsmithdev/generator-lwc-app#2]

**Comment by jsmithdev** [comment]
this should be done: f8e1473dbd09cd2b5ad16596976b8b35ad4c73ce

https://github.com/jsmithdev/generator-lwc-app/issues/1 -- this didn't specify "single page app" (SPA) but it doesn't use routes therefore I see it as a SPA. If im wrong or this was to mean something else just re-open and yell at me :+1:
