### ISSUE TITLE
Default Icons

### ISSUE THREAD

**Issue by jsmithdev** [jsmithdev/generator-lwc-app#3]
- [ ] Make some generic icons in all resolutions that the app may use (see manifest.json and index.html)

- [ ] Put them in [generator-lwc-app](https://github.com/jsmithdev/generator-lwc-app)/[generators](https://github.com/jsmithdev/generator-lwc-app/tree/main/generators)/[app](https://github.com/jsmithdev/generator-lwc-app/tree/main/generators/app)/[templates](https://github.com/jsmithdev/generator-lwc-app/tree/main/generators/app/templates)/resources/icons

- [ ] Use config.webpack.json to place them during build

- [ ]  Test

**Comment by effordDev** [comment]
![yo-lwc-16x16](https://user-images.githubusercontent.com/36901822/190259479-fc7db1d1-0c5d-4e79-b352-a61e3abca7eb.png)
![yo-lwc-32x32](https://user-images.githubusercontent.com/36901822/190259510-0f8cc801-8719-4966-851c-bcc513859cdd.png)
![yo-lwc-152x152](https://user-images.githubusercontent.com/36901822/190259524-7fa8c73d-80db-4f8f-8ec8-460d78aa732e.png)
![yo-lwc-180x180](https://user-images.githubusercontent.com/36901822/190259548-57ac669b-2580-4756-a264-b1ae33b0d0ae.png)
![yo-lwc-500x500](https://user-images.githubusercontent.com/36901822/190259566-0878cc4c-fc5d-4b25-b9ec-a6504b1b4b42.png)

**Comment by jsmithdev** [comment]
77bdfb29dd7797112c39df20bde287d2c2941b59 closes issue

thanks @effordDev :owl: :owl:
